import type { Metadata } from "next";
import "./styles/globals.css";
import Providers from "./providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>Meal Planner</h1>
        </nav>
        <Providers>
          <div id="content-wrapper">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
