import type { Metadata } from "next";
import Providers from "../providers/providers";
import Navbar from "../components/Navbar/Navbar";

// css
import "./styles/globals.css";
import './styles/components.css';
import './styles/variables.css';
import './styles/light-theme.css';
import './styles/atomics.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let session = await getSession();
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <Navbar/>
          <div id="content-wrapper">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
