import type { Metadata } from "next";
import Providers from "../providers/providers";
import Navbar from "../components/Navbar";

// css
import "./styles/globals.css";
import './styles/components.css';
import './styles/variables.css';
import './styles/dark-theme.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Providers>
          <div id="content-wrapper">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
